profiles/urls.py
from django.urls import path
from . import views

app_name =  "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow", views.FollowView.as_view(), name="follow"),
    path("<int:pk>/myprofile", views.MyProfileView.as_view(), name="myprofile"),
    path("users", views.UsersView.as_view(), name="users"),
]

til/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls,namespace="feed")),
    path('profile/', include(profiles_urls,namespace="profiles")),
    re_path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to="profiles",default="1")
    name = models.CharField(max_length=50)
    tagline = models.CharField(max_length=100)
    cover = ImageField(upload_to="profiles", default="1")

    def __str__(self):
        return (self.user.username)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if (created):
        Profile.objects.create(user=instance)

profiles/views.py
from typing import Any
from django import http
from django.contrib.auth.models import User
from django.views.generic import DetailView, View, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.db.models import Count, Q
from django.db.models import Subquery, OuterRef, IntegerField, BooleanField
from django.db.models.functions import Cast

from feed.models import Post
from followers.models import Follower
from profiles.models import Profile


class ProfileDetailView(DetailView):
    http_method_names=["get"]
    template_name="profile/detail.html"
    model = User
    context_object_name="user"
    slug_field="username"
    slug_url_kwarg="username"

    def dispatch(self, request, *args, **kwargs):
        self.request=request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user=self.get_object()
        context=super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count
        context['total_followers'] = Follower.objects.filter(following=user).count

        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists
        return context

class FollowView(LoginRequiredMixin, View):
    http_method_names=["post"]

    def post(self, request, *args, **kwargs):
        data=request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing Data")
    
        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")
        
        if data['action'] == "follow":
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,                    
                )
            except Follower.DoesNotExist:
                follower=None
            
            if follower:
                follower.delete()
                
        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })


class MyProfileView(LoginRequiredMixin, UpdateView):
    http_method_names=["get","put","post"]
    template_name="profile/myprofile.html"
    model = Profile
    fields=['name', 'tagline', 'id', 'image', 'cover']
    context_object_name="myprofile"
    slug_field="id"
    slug_url_kwarg="id"
    success_url="/"

    def dispatch(self, request, *args, **kwargs):
        self.request=request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user=self.get_object()
        context=super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user.user).count
        context['total_followers'] = Follower.objects.filter(following=user.user).count
        return context

class UsersView(ListView):
    http_method_names = ["get"]
    template_name="profile/users.html"
    model = Profile
    context_object_name = "users"
    queryset = Profile.objects.all().order_by('user')[0:60]
    
    def dispatch(self, request, *args, **kwargs):
        self.request=request
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        users = Profile.objects.filter(~Q(user=self.request.user)).order_by('user')[0:80]                
        posts = Post.objects.values("author").annotate(total_posts=Count("author"))
        followers = Follower.objects.values("following").annotate(total_followers=Count("following"))
        you_follow_qs = Follower.objects.values("following").annotate(you_follow=Count("following", filter=Q(followed_by=self.request.user)))
       # you_follow_sub= you_follow_qs.filter(followed_by=self.request.user)
        #you_follow = Follower.objects.filter(followed_by=self.request.user)
        #print(you_follow_qs)

        subquery_qs_posts = posts.filter(author=OuterRef('id'))
        subquery_qs_followers = followers.filter(following=OuterRef('id'))
        subquery_qs_you_follow = you_follow_qs.filter(following=OuterRef('id'))

       # print(subquery_qs_followers)
        #print(subquery_qs_you_follow)

        context['users'] = users.annotate(total_posts = Cast(Subquery(subquery_qs_posts.values('total_posts')[:1]), output_field=IntegerField()),
                                        total_followers = Cast(Subquery(subquery_qs_followers.values('total_followers')[:1]), output_field=IntegerField()),
                                        you_follow = Cast(Subquery(subquery_qs_you_follow.values('you_follow')[:1]), output_field=IntegerField()))
    
        return context

    

profiles/templates/profile/detail.html
{% extends "base.html" %}
{% load thumbnail   %}

{% block title %} Detail - {{ user.username }} {% endblock title%}
{% block header %} Profile of {{ user.username }} {% endblock %}
{% block breadcrumb %} Home -> Detail {% endblock %}

{% block body %}
    <!-- component -->
<div class="rounded rounded-t-lg overflow-hidden shadow max-w-md my-3 mx-auto bg-white" style="max-width: 20rem;">
    <img src="{{ user.profile.cover.url }}" class="w-full" />
    <div class="flex justify-center -mt-8">
    {% thumbnail user.profile.image "100x100" crop="center" as im %}
        <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3" alt="avatar">
    {% endthumbnail %}   
  </div>
  <div class="text-center px-3 pb-6 pt-2">
      <h3 class="text-blacktext-sm bold font-sans">{{ user.username }}</h3>

      {% if request.user.is_authenticated %}
        {% if request.user != user %}
      <button class="bg-blue-600 hover:bg-blue-700 px-3 py-1 rounded text-white js-follow" data-username="{{ user.username }}" 
      data-action={% if you_follow %} "un" {% endif %} "follow" data-url="{% url 'profiles:follow' user.username %}" type="button">
      {% if you_follow %}
        Unfollow
      {% else %}
        Follow
      {% endif %}
      </button>
        {%endif%}
        {% endif %}

      <p class="mt-2 font-sans font-light text-grey-dark">{{ user.profile.tagline }}</p>
  </div>
    <div class="flex justify-center pb-3 text-grey-dark">
    <div class="text-center mr-3 border-r pr-3">
      <h2>{{ total_posts }}</h2>
      <span>Posts</span>
    </div>
    <div class="text-center">
      <h2>{{ total_followers }}</h2>
      <span>Followers</span>
    </div>
    </div>
  </div>
{% endblock body %}

profiles/templates/profile/myprofile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block header %} My Profile {% endblock header %}
{% block breadcrumb %} My Profile {% endblock %}

{% block body %}

<form method="POST" enctype="multipart/form-data" class="bg-white shadow-lg rounded-lg my-6 mx-auto" style="width: 80%;">
    <div class="bg-gradient-to-b from-blue-500 to-blue-400 opacity-75" style="padding: 10px;">
        <h2 class="font-semibold text-white text-lg">Profile Details</h2>
    </div>
    {% csrf_token %} 
    <div class="p-3">
        {% for field in form %}
            <div class="fieldWrapper" style="display: grid; grid-template-columns: 10% 90%;">
                {{ field.errors }}  
                <div style="padding-left: 10px;"> {{ field.label_tag }}:</div>

                {% if field.name != "name" and field.name != "tagline" %}
                    <div class="border"> {{ field }}</div>    
                {% else %}    
                    {% if field.name == "name" %}
                        <div class="border"> 
                            <input type="text" name="name" value="{{ field.value }}" maxlength="50" required="" id="id_name" style="width: 100%;">
                        </div>
                    {% else %}
                        <div class="border"> 
                            <input type="text" name="tagline" value="{{ field.value }}" maxlength="100" required="" id="id_tagline" style="width: 100%;">
                        </div>
                    {% endif %} 
                {% endif %}                   
            </div>
        {% endfor %}  
        <div class="flex justify-between">
            <span>&nbsp;</span>
            <div style="margin-top: 20px; margin-bottom: 20px;">
                <button class="bg-blue-400 hover:bg-blue-500 text-gray-100 p-3 rounded-full 
                tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-500" 
                style="margin-left: 10px" type="submit">Save Profile</button>
                <button class="js-toggle-card-modal bg-blue-400 hover:bg-blue-500 text-gray-100 p-3 rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-500" style="margin-left: 10px" type="button">View Card</button>
            </div> 
        </div>
    </div>      
    </form>

    <div 
        class="modal h-screen w-full fixed left-0 top-0 flex justify-center items-center bg-black bg-opacity-70 hidden js-card-modal">
        <!-- modal -->
        <div class="bg-white rounded shadow-lg w-10/12 md:w-1/3">
            <!-- modal header -->
            <div class="border-b px-4 py-2 flex justify-between items-center bg-gradient-to-b from-blue-500 to-blue-400 opacity-75">
                <h3 class="font-semibold text-lg text-white">My Profile</h3>
                <button class="text-black close-modal js-toggle-card-modal">&cross;</button>
            </div>
            <!-- modal body -->
            <!-- component -->
            <div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3 mx-auto shadow" style="max-width: 20rem;">
                <img src="{{ myprofile.cover.url }}" class="w-full" />
                <div class="flex justify-center -mt-8">
                    {% thumbnail myprofile.image "100x100" crop="center" as im %}
                        <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">		
                    {% endthumbnail %}  
                </div>
                <div class="text-center px-3 pb-6 pt-2">
                    <h3 class="text-sm bold font-sans">{{ myprofile.name }}</h3>
                    <p class="mt-2 font-sans font-light">{{ myprofile.tagline }}</p>
                </div>
                <div class="flex justify-center pb-3">
                    <div class="text-center mr-3 border-r pr-3">
                        <h2>{{ total_posts }}</h2>
                        <span>Posts</span>
                    </div>
                    <div class="text-center">
                        <h2>{{ total_followers }}</h2>
                        <span>Followers</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}

profiles/templates/profile/users.html
{% extends "base.html" %}

{% block title %}
Users
{% endblock %}

{% block header %} All Users {% endblock %}
{% block breadcrumb %} Users {% endblock %}

{% block body %}
<div id="users-container" class="p-3" style="display: grid; grid-template-columns: 33% 33% 33%;">
    {% for user in users %}
        {% include "includes/user.html" with user=user %}
    {% endfor %}
</div>
{% endblock %}