feed/urls.py
from django.urls import path
from . import views

app_name="feed"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name =  "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow", views.FollowView.as_view(), name="follow"),
    path("<int:pk>/myprofile", views.MyProfileView.as_view(), name="myprofile"),
    path("users", views.UsersView.as_view(), name="users"),
]

til/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls,namespace="feed")),
    path('profile/', include(profiles_urls,namespace="profiles")),
    re_path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

til/templates/includes/post.html
{% load thumbnail %}

<!-- post card -->
<div class="flex bg-white shadow-lg rounded-lg mx-4 md:mx-auto max-w-md md:max-w-2xl" style="margin-top: 20px;"><!--horizantil margin is just for display-->
    <div class="flex items-start px-4 py-6">       
          <div class="flex items-center justify-between">
            
                <a href="{% url 'profiles:detail' post.author.username %}" style="width: 8rem;" class="shrink-0">                    
                    {% thumbnail post.author.profile.image "100x100" crop="center" as im %}
                    <img class="w-12 h-12 rounded-full object-cover shadow mx-auto" src="{{im.url}}" alt="avatar">
                    {% endthumbnail %}            
                    <h2 class="text-lg font-semibold text-gray-900 text-center">{{post.author.username}} </h2>
                </a>
                <span>&nbsp;</span> 
            <div>  
                <small class="text-sm text-gray-700">{{ post.date }}</small>
                
                {% if show_detail_link%}
                    <p class="mt-3 text-gray-700 text-md" style="width: 50ch; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                        {{ post.text }}
                    </p>
                    <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
                        Read more...
                    </a>     
                {% else %} 
                <p class="mt-3 text-gray-700 text-md">
                    {{ post.text }}
                </p>
                {% endif %}
            </div>
        
       </div>
    </div>
 </div>

til/templates/includes/user.html
 {% load thumbnail %}

 <!-- component -->
 <div class="rounded rounded-t-lg overflow-hidden shadow max-w-md my-3 bg-white" style="max-width: 20rem; margin: 10px;">
    <img src="{{ user.cover.url }}" class="w-full" style="height: 10rem; width: 20rem;" />
    <div class="flex justify-center -mt-8">
    {% thumbnail user.image "100x100" crop="center" as im %}
        <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3" alt="avatar">
    {% endthumbnail %}   
    </div>
    <div class="text-center px-3 pb-6 pt-2">
        <h3 class="text-blacktext-sm bold font-sans my-3">{{ user }}</h3>

        {% if request.user.is_authenticated %}        
                <button class="bg-blue-400 hover:bg-blue-500 text-gray-100 p-3 rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-500 js-follow" style="margin-left: 10px" data-url="{% url 'profiles:follow' user %}" data-username="{{ user }}" 
                data-action={% if user.you_follow %} "un" {% endif %} "follow"  type="button">
            {% if user.you_follow %}
                Unfollow
            {% else %}
                Follow
            {% endif %}
                </button>
        {% endif %}

      <p class="mt-2 font-sans font-light text-grey-dark">{{ user.tagline }}</p>
  </div>
    <div class="flex justify-center pb-3 text-grey-dark">
    <div class="text-center mr-3 border-r pr-3">
      <h2>{{ user.total_posts }}</h2>
      <span>Posts</span>
    </div>
    <div class="text-center">
      <h2>{{ user.total_followers }}</h2>
      <span>Followers</span>
    </div>
    </div>
  </div>