feed/urls.py
from django.urls import path
from . import views

app_name="feed"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name =  "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow", views.FollowView.as_view(), name="follow"),
    path("<int:pk>/myprofile", views.MyProfileView.as_view(), name="myprofile"),
    path("users", views.UsersView.as_view(), name="users"),
]

til/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls,namespace="feed")),
    path('profile/', include(profiles_urls,namespace="profiles")),
    re_path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

til/templates/base.html
{% load static %}
{% load thumbnail %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="{% static 'css/output.css' %}" rel="stylesheet">
</head>

<body>
    <!-- component -->
    <div class="flex bg-white">
        <div class="md:flex w-2/5 md:w-1/4 h-screen border-r hidden bg-gradient-to-b from-blue-500 to-blue-400 opacity-75">
            <div class="mx-6 py-10">
                <h1 class="text-2xl font-bold mb-10 cursor-pointer duration-150 text-white text-center">TIL</h1>
                <div>
                    <a class="flex space-x-2 mt-10 cursor-pointer hover:text-[#EC5252] duration-150 text-white" href="/">
                        <i class="bx bx-home bx-sm"></i>
                        <span class="font-semibold">Home</span>
                    </a>
                    {% if request.user.is_authenticated %}
                    <a class="flex space-x-2 mt-10 cursor-pointer hover:text-[#EC5252] duration-150 text-white"
                        href="{% url 'profiles:myprofile' request.user.id %}">
                        <i class="bx bx-user-circle bx-sm"></i>
                        <span class="font-semibold">My Profie</span>
                    </a>                   
                    <a class="flex space-x-2 mt-10 cursor-pointer hover:text-[#EC5252] duration-150 js-toggle-modal text-white"
                        href="{% url 'feed:new_post' %}">
                        <i class="bx bx-message-add bx-sm"></i>
                        <span class="font-semibold">New Post</span>
                    </a>
                    <a class="flex space-x-2 mt-10 cursor-pointer hover:text-[#EC5252] duration-150 text-white"
                        href="{% url 'profiles:users' %}">
                        <i class="bx bx-user-pin bx-sm"></i>
                        <span class="font-semibold">Users</span>
                    </a>                        
                    {% endif %}
                    <a class="flex space-x-2 mt-10 cursor-pointer hover:text-[#EC5252] duration-150 text-white"
                        href="{% url 'account_logout' %}">
                        <i class="bx bx-log-out bx-sm"></i>
                        <span class="font-semibold">Logout</span>
                    </a> 
                </div>
            </div>
        </div>
        <main class="min-h-screen w-full border-l" style="background-color:#ececec">
            <div>
                <div class="flex bg-white shadow-lg p-3 justify-between" style="width: 100%;">
                    <div>
                        <h1 style="font-size: 20px;">{% block header %}{% endblock %}</h1>
                        <small class="text-blue-600">{% block breadcrumb %}{% endblock %}</small>
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="flex justify-between my-auto">
                        {% thumbnail request.user.profile.image "100x100" crop="center" as im %}
                            <img class="w-12 h-12 rounded-full object-cover shadow" src="{{im.url}}" alt="avatar">
                        {% endthumbnail %}    
                        <h1 style="margin: 10px;"> {{ request.user }} </h1>
                    </div>
                    {% endif %}
                </div>
                {% if request.user.is_authenticated %}
                {% block body %}
                {% endblock %}

                <!-- component -->
                <div
                    class="modal h-screen w-full fixed left-0 top-0 flex justify-center items-center bg-black bg-opacity-70 hidden js-modal">
                    <!-- modal -->
                    <div class="bg-white rounded shadow-lg w-10/12 md:w-1/3">
                        <!-- modal header -->
                        <div class="border-b px-4 py-2 flex justify-between items-center bg-gradient-to-b from-blue-500 to-blue-400 opacity-75">
                            <h3 class="font-semibold text-lg text-white">New Post</h3>
                            <button class="text-black close-modal js-toggle-modal">&cross;</button>
                        </div>
                        <!-- modal body -->

                        <div class="px-3">
                            <textarea class="border-2 border-blue-500 my-4 w-full js-post-text"
                                placeholder="Enter your post" rows="3" maxlength="240" data-post-url="{% url 'feed:new_post' %}"></textarea>
                        </div>

                        <div class="flex justify-end items-center w-100 border-t p-3">                            
                                <button class="bg-blue-400 hover:bg-blue-500 text-gray-100 p-3 
                                rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in 
                                duration-500 js-submit" style="margin-left: 10px" type="submit">Save Post</button>
                            
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>

        </main>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/main.js' %}?09282023"></script>

</body>

</html>